### PR TITLE
Python 3 Compatibility

### PR DESCRIPTION
**Pull request by lambacck**
Hello,

Here is Python 3 compatibility with tests for both the c extension and the native python version. Additionally the benchmark is now easily runnable via tox on python 2.7, 3.6 and pypy.

If you are no longer interested in maintaining this library I'd be happy to take it on.

### CODE REVIEW

**Comment by palinarachkouskaya** [comment]
Hello.

Why this PR is still not merged?

**Comment by dahlia** [comment]
This repository is dead, and it seems @heroku's fork is the really alive project.  As I have no motivation to maintain this project, I hope to transfer the ownership to real maintainers. Who's responsible for @heroku's fork? @sigmavirus24 @lambacck 

If someone continuously taking care on @heroku's fork is willing to take over the project, I am going to give them the full permission on PyPI (<https://pypi.org/project/pghstore/>).

**Comment by sigmavirus24** [comment]
@dahlia I spoke with @lambacck and we'd be happy to take over maintenance. We're not likely to do a lot of development on the project, but we're going to keep it stable and up-to-date as necessary. You can copy our usernames from https://pypi.org/project/salesforce-bulk/ or for simplicity:

- `lambacck`
- `graffatcolmingov` (this is me)

**Comment by dahlia** [comment]
@sigmavirus24 Thank you for the response!  I just give you the ownership on the PyPI *pghstore* package.  Check please.

As @heroku's repository became the upstream, I'm going to close this pull request.

**Pull request closed without merging**
